## Intro to Numpy

#### A numpy array consists of data elements of only one type. It is fixed in size but mutable.

### Import the Numpy library

In [1]:
import numpy as np

### Cast a python list to a numpy array

In [2]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

### Check the type of the array

In [3]:
type(a)

numpy.ndarray

### Check the type of the elements and other attributes of the array

In [4]:
a.dtype

dtype('int64')

In [5]:
a.size

5

In [6]:
a.ndim

1

In [7]:
a.shape

(5,)

#### You can do slicing on it in the same way that you do slicing in Python lists.

### Numpy Statistical Functions

In [8]:
b = np.array([0,1,2,3,4,5])
mean = b.mean()
mean

np.float64(2.5)

In [9]:
standard_deviation = b.std()
standard_deviation

np.float64(1.707825127659933)

In [10]:
max_value = b.max()
max_value

np.int64(5)

In [11]:
min_value = b.min()
min_value

np.int64(0)

### Numpy Array Operations

#### Array Addition

In [12]:
u = np.array([0,1])
v = np.array([1,0])

add = np.add(u,v)
add

array([1, 1])

#### Scalar Addition

In [13]:
scalar_add  = 2 + u  #Adds 2 to each element of u
scalar_add

array([2, 3])

#### Array Subtraction

In [14]:
sub = np.subtract(u,v)
sub

array([-1,  1])

#### Array Multiplication


In [15]:
mult = np.multiply(u,v)
mult

array([0, 0])

#### Scalar Multiplication

In [16]:
scalar_mult = 5 * u #Multiplies each element of u by 5
scalar_mult

array([0, 5])

#### Array Division

In [17]:
a = np.array([10, 20, 30])
b = np.array([2, 10, 5])

c = np.divide(a, b)
c

array([5., 2., 6.])

#### Dot Product / Scalar Product

In [18]:
d = np.array([1, 2])
e = np.array([3, 2])

f = np.dot(d, e)
f

np.int64(7)

### Mathematical Functions

In [19]:
np.linspace(-2,2, num = 5) #Generates 5 numbers between -2 and 2

array([-2., -1.,  0.,  1.,  2.])