## Intro to NumPy

#### A numpy array consists of data elements of only one type. It is fixed in size but mutable.

### Import the NumPy library

In [43]:
import numpy as np

### Cast a python 1D list to a numpy array

In [44]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

### Check the type of the array

In [45]:
type(a)

numpy.ndarray

### Check the type of the elements and other attributes of the array

In [46]:
a.dtype

dtype('int64')

In [47]:
a.size

5

In [48]:
a.ndim

1

In [49]:
a.shape

(5,)

#### You can do slicing on it in the same way that you do slicing in Python lists.

### Numpy Statistical Functions

In [50]:
b = np.array([0,1,2,3,4,5])
mean = b.mean()
mean

np.float64(2.5)

In [51]:
standard_deviation = b.std()
standard_deviation

np.float64(1.707825127659933)

In [52]:
max_value = b.max()
max_value

np.int64(5)

In [53]:
min_value = b.min()
min_value

np.int64(0)

### Numpy 1D Array (Vector) Operations

#### Vector Addition

In [54]:
u = np.array([0,1])
v = np.array([1,0])

vector_add = np.add(u,v)
vector_add

array([1, 1])

#### Scalar Addition

In [55]:
scalar_add  = 2 + u  #Adds 2 to each element of u
scalar_add

array([2, 3])

#### Vector Subtraction

In [56]:
vector_sub = np.subtract(u,v)
vector_sub

array([-1,  1])

#### Scalar Subtraction

In [57]:
scalar_sub  = u - 7  #Subtract 7 from each element of u
scalar_sub

array([-7, -6])

#### Vector Product (Hadamard Product)


In [58]:
mult = np.multiply(u,v)
mult

array([0, 0])

#### Scalar Product

In [59]:
scalar_mult = 5 * u #Multiplies each element of u by 5
scalar_mult

array([0, 5])

#### Vector Division

In [60]:
a = np.array([10, 20, 30])
b = np.array([2, 10, 5])

c = np.divide(a, b)
c

array([5., 2., 6.])

#### Dot Product

In [61]:
d = np.array([1, 2])
e = np.array([3, 2])

f = np.dot(d, e)
f

np.int64(7)

### Mathematical Functions

In [62]:
np.linspace(-2,2, num = 5) #Generates 5 numbers between -2 and 2

array([-2., -1.,  0.,  1.,  2.])