### Import the Numpy library

In [1]:
import numpy as np

### Create a 2D Python list and cast it to a NumPy array

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
b = np.array(a)
b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
b.ndim    # dimension or rank of the array

2

In [4]:
b.shape

(3, 3)

In [5]:
b.size

9

In [ ]:
b[1][2] # Access the element on the second row and third column

np.int64(23)

### Numpy 2D Array (Vector) Operations

#### Vector Addition

In [7]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])
z = np.add(X, Y) # Element-wise addition
z

array([[3, 1],
       [1, 3]])

#### Scalar Addition

In [ ]:
W = X + 2 # Broadcasting. Add 2 to each element of X

array([[3, 2],
       [2, 3]])

#### Vector Multiplication (Hadamard Product)

In [9]:
V = np.multiply(X, Y) # Element-wise multiplication
V

array([[2, 0],
       [0, 2]])

#### Scalar Multiplication

In [10]:
U = 2 * Y # Broadcasting. Multiply each element of Y by 2
U

array([[4, 2],
       [2, 4]])

#### Dot Product

In [11]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [12]:

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [14]:
C = np.dot(A, B) # Matrix multiplication
C

array([[0, 2],
       [0, 2]])

#### Transpose

In [15]:
D = np.array([[1,1],[2,2],[3,3]])
D

array([[1, 1],
       [2, 2],
       [3, 3]])

In [16]:
# Get the transposed of D

D.T

array([[1, 2, 3],
       [1, 2, 3]])